# Generated by Django 4.1.7 on 2023-03-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0006_alter_news_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
    ]
