# Generated by Django 4.0 on 2023-04-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0009_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_uz',
        ),
    ]
